[package]
authors = ["Zongmin Lei <leizongmin@gmail.com>"]
description = "NoSQL embedded database on top of RocksDB"
edition = "2018"
homepage = "https://github.com/leizongmin/simpledb"
keywords = ["rocksdb", "nosql"]
license = "MIT"
name = "simpledb"
repository = "https://github.com/leizongmin/simpledb"
version = "0.1.6"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.1.0"
rocksdb = "0.17.0"

[dev-dependencies]
rand = "0.8.5"
