[package]
name = "simpledb"
version = "0.1.3"
authors = ["Zongmin Lei <leizongmin@gmail.com>"]
edition = "2018"
description = "NoSQL embedded database on top of RocksDB"
keywords = ["rocksdb", "nosql"]
license = "MIT"
repository = "https://github.com/leizongmin/simpledb"
homepage = "https://github.com/leizongmin/simpledb"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocksdb = "0.15"
bytes = "0.6"

[dev-dependencies]
rand = "0.8"
