name: Rust

permissions:
  deployments: write
  contents: write

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          components: clippy
          override: true

    - uses: actions/checkout@v3

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features

    - name: Run benchmark
      run: cargo bench -- --output-format bencher | tee criterion.txt

    - name: push benchmark github page
      uses: benchmark-action/github-action-benchmark@v1
      with:
          tool: 'cargo'
          output-file-path: criterion.txt
          comment-on-alert: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
